{{- $secretName := .Values.secret.name }}
{{- $existingSecret := lookup "v1" "Secret" .Release.Namespace $secretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
type: Opaque
data:
  {{- if $existingSecret }}
  {{ .Values.mysql.auth.passwordKey }}: {{ index $existingSecret.data .Values.mysql.auth.passwordKey }}
  {{ .Values.mysql.auth.rootPasswordKey }}: {{ index $existingSecret.data .Values.mysql.auth.rootPasswordKey }}
  {{- else }}
  {{ .Values.mysql.auth.passwordKey }}: {{ randAlphaNum 16 | b64enc | quote }}
  {{ .Values.mysql.auth.rootPasswordKey }}: {{ randAlphaNum 24 | b64enc | quote }}
  {{- end }}
