{{- if .Values.agent_api.enable }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "observability.agent_api.name" . }}
  labels:
    {{- include "observability.labels" . | nindent 4 }}
    {{- include "observability.agent_api.selectorLabels" . | nindent 4 }}
    {{- include "observability.scaledownPreDeploy" .Values.agent_api | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.agent_api.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "observability.agent_api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        # Used to force Helm to trigger a re-deploy despite this manifest haven't changed
        timestamp: {{ now | quote }}
        {{- with .Values.agent_api.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "observability.agent_api.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "observability.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.agent_api.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ include "observability.agent_api.name" . }}
          securityContext:
            {{- toYaml .Values.agent_api.securityContext | nindent 12 }}
          image: {{ include "observability.agent_api.image" . | quote }}
          imagePullPolicy: {{ .Values.agent_api.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.agent_api.service.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.agent_api.resources | nindent 12 }}
          env:
            {{- include "observability.environment.base" . | nindent 12 }}
            {{- include "observability.environment.flask" . | nindent 12 }}
            {{- include "observability.environment.database" . | nindent 12 }}
            - name: GUNICORN_CMD_ARGS
              value: "--bind 0.0.0.0:{{ .Values.agent_api.service.port }}"
            {{- if .Values.agent_api.hostname }}
            - name: AGENT_API_HOSTNAME
              value: {{ tpl .Values.agent_api.hostname . | quote }}
            {{- end }}
            {{- if ne .Values.observability.config_type "minikube" }}
            - name: AGENT_API_KEY_FLASK_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.observability.keys_secrets_name | quote }}
                  key: AGENT_API_KEY_FLASK_SECRET
            {{- end }}
          command: [ "/dk/bin/gunicorn" ]
          args: [ "-c", "/dk/gunicorn.conf.py", "agent_api.app:app" ]
          readinessProbe:
            periodSeconds: 20
            timeoutSeconds: 5
            httpGet:
              path: /agent/readyz
              port: 5003
              httpHeaders:
                {{- if .Values.agent_api.hostname }}
                - name: Host
                  value: {{ tpl .Values.agent_api.hostname . | quote }}
                {{- end }}
      {{- with .Values.agent_api.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.agent_api.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.agent_api.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "observability.agent_api.name" . }}
  labels:
    {{- include "observability.labels" . | nindent 4 }}
    {{- include "observability.agent_api.selectorLabels" . | nindent 4 }}
spec:
  type: {{ .Values.agent_api.service.type }}
  ports:
    - name: http
      port: {{ .Values.agent_api.service.port }}
      targetPort: http
      protocol: TCP
      {{- with .Values.agent_api.service.nodePort }}
      nodePort: {{ . }}
      {{- end }}
  selector:
    {{- include "observability.agent_api.selectorLabels" . | nindent 4 }}
{{- end }}
