{{- range $index, $job := .Values.cli_hook.enable }}
apiVersion: batch/v1
kind: Job
metadata:
  name: cli-job-{{ default $index .name }}
  annotations:
    "helm.sh/hook": {{ join ", " .phases }}
    "helm.sh/hook-weight": {{ default 0 .weight | quote }}
    "helm.sh/hook-delete-policy": hook-succeeded, before-hook-creation
spec:
  template:
    metadata:
      name: cli-job-{{ default $index .name }}
    spec:
      restartPolicy: Never
      {{- with $.Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "observability.serviceAccountName" $ }}
      containers:
        - name: cli-hook
          image: {{ include "observability.cli_hook.image" $ | quote }}
          imagePullPolicy: {{ $.Values.cli_hook.image.pullPolicy }}
          env:
            {{- include "observability.environment.base" $ | nindent 12 }}
            {{- include "observability.environment.database" $ | nindent 12 }}
            {{- include "observability.environment.pythonpath" $ | nindent 12 }}
          {{- with $.Values.extraVolumeMounts }}
          volumeMounts:
            {{ toYaml . | nindent 12 }}
          {{- end }}
          command:
            {{- range .command }}
            - {{ . | quote -}}
            {{- end }}
          args:
            {{- range .args }}
            - {{ . | quote -}}
            {{- end }}
      {{- with $.Values.extraVolumes }}
      volumes:
        {{ toYaml . | nindent 8 }}
      {{- end }}
---
{{- end }}
