export enum TestgenTestType {
  AlphaTruncation = 'Alpha_Trunc',
  AverageShift = 'Avg_Shift',
  ConstantMatch = 'Constant',
  DailyRecords = 'Daily_Record_Ct',
  DecimalTruncation = 'Dec_Trunc',
  DateCount = 'Distinct_Date_Ct',
  ValueCount = 'Distinct_Value_Ct',
  EmailFormat = 'Email_Format',
  PastDates = 'Future_Date',
  FutureYear = 'Future_Date_1Y',
  NewShift = 'Incr_Avg_Shift',
  AllValues = 'LOV_All',
  ValueMatch = 'LOV_Match',
  MinimumDate = 'Min_Date',
  MinimumValue = 'Min_Val',
  PercentMissing = 'Missing_Pct',
  MonthlyRecords = 'Monthly_Rec_Ct',
  OutliersAbove = 'Outlier_Pct_Above',
  OutliersBelow = 'Outlier_Pct_Below',
  PatternMatch = 'Pattern_Match',
  Recency = 'Recency',
  RequiredEntry = 'Required',
  RowCount = 'Row_Ct',
  RowRange = 'Row_Ct_Pct',
  StreetAddress = 'Street_Addr_Pattern',
  UniqueValues = 'Unique',
  PercentUnique = 'Unique_Pct',
  USState = 'US_State',
  WeeklyRecords = 'Weekly_Rec_Ct',
  CustomCondition = 'Condition_Flag',
  AggregateMinimum = 'AGG MATCH NO DROPS',
  AggregateMatch = 'AGG MATCH SAME',
  ComboMatch = 'DATA_MATCH',
  PriorMatch = 'PRIOR MATCH',
  DistributionShift = 'RELATIVE ENTROPY',
  TimeframeMinimum = 'WINDOW MATCH NO DROPS',
  TimeframeMatch = 'WINDOW MATCH SAME',
  CustomTest = 'CUSTOM',
}

export const testTypeHelpLink: {[type in TestgenTestType]: string} = {
  [TestgenTestType.AlphaTruncation]: 'https://docs.datakitchen.io/article/dataops-testgen-help/validity-tests/a/h3_1983327887',
  [TestgenTestType.AverageShift]: 'https://docs.datakitchen.io/article/dataops-testgen-help/consistency-tests/a/h3_44239721',
  [TestgenTestType.ConstantMatch]: 'https://docs.datakitchen.io/article/dataops-testgen-help/validity-tests/a/h3_746819470',
  [TestgenTestType.DailyRecords]: 'https://docs.datakitchen.io/article/dataops-testgen-help/completeness-tests/a/h3_1178577173',
  [TestgenTestType.DecimalTruncation]: 'https://docs.datakitchen.io/article/dataops-testgen-help/validity-tests/a/h3__373442559',
  [TestgenTestType.DateCount]: 'https://docs.datakitchen.io/article/dataops-testgen-help/timeliness-tests/a/h3__1877443033',
  [TestgenTestType.ValueCount]: 'https://docs.datakitchen.io/article/dataops-testgen-help/validity-tests/a/h3_899252010',
  [TestgenTestType.EmailFormat]: 'https://docs.datakitchen.io/article/dataops-testgen-help/validity-tests/a/h3__2047022636',
  [TestgenTestType.PastDates]: 'https://docs.datakitchen.io/article/dataops-testgen-help/timeliness-tests/a/h3_1413556254',
  [TestgenTestType.FutureYear]: 'https://docs.datakitchen.io/article/dataops-testgen-help/timeliness-tests/a/h3__928848685',
  [TestgenTestType.NewShift]: 'https://docs.datakitchen.io/article/dataops-testgen-help/accuracy-tests/a/h3__340398188',
  [TestgenTestType.AllValues]: 'https://docs.datakitchen.io/article/dataops-testgen-help/validity-tests/a/h3_950119229',
  [TestgenTestType.ValueMatch]: 'https://docs.datakitchen.io/article/dataops-testgen-help/validity-tests/a/h3_1940362535',
  [TestgenTestType.MinimumDate]: 'https://docs.datakitchen.io/article/dataops-testgen-help/validity-tests/a/h3_226899607',
  [TestgenTestType.MinimumValue]: 'https://docs.datakitchen.io/article/dataops-testgen-help/validity-tests/a/h3_1851564010',
  [TestgenTestType.PercentMissing]: 'https://docs.datakitchen.io/article/dataops-testgen-help/completeness-tests/a/h3__52647518',
  [TestgenTestType.MonthlyRecords]: 'https://docs.datakitchen.io/article/dataops-testgen-help/completeness-tests/a/h3_1071121640',
  [TestgenTestType.OutliersAbove]: 'https://docs.datakitchen.io/article/dataops-testgen-help/accuracy-tests/a/h3__349278480',
  [TestgenTestType.OutliersBelow]: 'https://docs.datakitchen.io/article/dataops-testgen-help/accuracy-tests/a/h3__1451463736',
  [TestgenTestType.PatternMatch]: 'https://docs.datakitchen.io/article/dataops-testgen-help/validity-tests/a/h3_1861513634',
  [TestgenTestType.Recency]: 'https://docs.datakitchen.io/article/dataops-testgen-help/timeliness-tests/a/h3_1607751959',
  [TestgenTestType.RequiredEntry]: 'https://docs.datakitchen.io/article/dataops-testgen-help/completeness-tests/a/h3__1487174321',
  [TestgenTestType.RowCount]: 'https://docs.datakitchen.io/article/dataops-testgen-help/completeness-tests/a/h3__568091024',
  [TestgenTestType.RowRange]: 'https://docs.datakitchen.io/article/dataops-testgen-help/completeness-tests/a/h3__1273504328',
  [TestgenTestType.StreetAddress]: 'https://docs.datakitchen.io/article/dataops-testgen-help/validity-tests/a/h3_1905175740',
  [TestgenTestType.UniqueValues]: 'https://docs.datakitchen.io/article/dataops-testgen-help/uniqueness-tests/a/h3__358603211',
  [TestgenTestType.PercentUnique]: 'https://docs.datakitchen.io/article/dataops-testgen-help/uniqueness-tests/a/h3__1169623539',
  [TestgenTestType.USState]: 'https://docs.datakitchen.io/article/dataops-testgen-help/validity-tests/a/h3__1015410244',
  [TestgenTestType.WeeklyRecords]: 'https://docs.datakitchen.io/article/dataops-testgen-help/completeness-tests/a/h3_592883938',
  [TestgenTestType.CustomCondition]: 'https://docs.datakitchen.io/article/dataops-testgen-help/validity-tests/a/h3_746819470',
  [TestgenTestType.AggregateMinimum]: 'https://docs.datakitchen.io/article/dataops-testgen-help/accuracy-tests/a/h3__1106060513',
  [TestgenTestType.AggregateMatch]: 'https://docs.datakitchen.io/article/dataops-testgen-help/consistency-tests/a/h3_1888438828',
  [TestgenTestType.ComboMatch]: 'https://docs.datakitchen.io/article/dataops-testgen-help/validity-tests/a/h3__1305588315',
  [TestgenTestType.PriorMatch]: 'https://docs.datakitchen.io/article/dataops-testgen-help/consistency-tests/a/h3__68646033',
  [TestgenTestType.DistributionShift]: 'https://docs.datakitchen.io/article/dataops-testgen-help/consistency-tests/a/h3_1158272005',
  [TestgenTestType.TimeframeMinimum]: 'https://docs.datakitchen.io/article/dataops-testgen-help/consistency-tests/a/h3__328401568',
  [TestgenTestType.TimeframeMatch]: 'https://docs.datakitchen.io/article/dataops-testgen-help/consistency-tests/a/h3__1310439177',
  [TestgenTestType.CustomTest]: 'https://docs.datakitchen.io/article/dataops-testgen-help/accuracy-tests/a/h3__1168279791',
};
