export enum TestgenTestType {
  AlphaTruncation = 'Alpha_Trunc',
  AverageShift = 'Avg_Shift',
  ConstantMatch = 'Constant',
  DailyRecords = 'Daily_Record_Ct',
  DecimalTruncation = 'Dec_Trunc',
  DateCount = 'Distinct_Date_Ct',
  ValueCount = 'Distinct_Value_Ct',
  EmailFormat = 'Email_Format',
  PastDates = 'Future_Date',
  FutureYear = 'Future_Date_1Y',
  NewShift = 'Incr_Avg_Shift',
  AllValues = 'LOV_All',
  ValueMatch = 'LOV_Match',
  MinimumDate = 'Min_Date',
  MinimumValue = 'Min_Val',
  PercentMissing = 'Missing_Pct',
  MonthlyRecords = 'Monthly_Rec_Ct',
  OutliersAbove = 'Outlier_Pct_Above',
  OutliersBelow = 'Outlier_Pct_Below',
  PatternMatch = 'Pattern_Match',
  Recency = 'Recency',
  RequiredEntry = 'Required',
  RowCount = 'Row_Ct',
  RowRange = 'Row_Ct_Pct',
  StreetAddress = 'Street_Addr_Pattern',
  UniqueValues = 'Unique',
  PercentUnique = 'Unique_Pct',
  USState = 'US_State',
  WeeklyRecords = 'Weekly_Rec_Ct',
  CustomCondition = 'Condition_Flag',
  AggregateMinimum = 'AGG MATCH NO DROPS',
  AggregateMatch = 'AGG MATCH SAME',
  ComboMatch = 'DATA_MATCH',
  PriorMatch = 'PRIOR MATCH',
  DistributionShift = 'RELATIVE ENTROPY',
  TimeframeMinimum = 'WINDOW MATCH NO DROPS',
  TimeframeMatch = 'WINDOW MATCH SAME',
  CustomTest = 'CUSTOM',
}

export const testTypeHelpLink: {[type in TestgenTestType]: string} = {
  [TestgenTestType.AlphaTruncation]: 'https://docs.datakitchen.io/article/dataops-testgen-help/validity-tests/a/alpha-truncation',
  [TestgenTestType.AverageShift]: 'https://docs.datakitchen.io/article/dataops-testgen-help/consistency-tests/a/average-shift',
  [TestgenTestType.ConstantMatch]: 'https://docs.datakitchen.io/article/dataops-testgen-help/validity-tests/a/constant-match',
  [TestgenTestType.DailyRecords]: 'https://docs.datakitchen.io/article/dataops-testgen-help/completeness-tests/a/daily-records',
  [TestgenTestType.DecimalTruncation]: 'https://docs.datakitchen.io/article/dataops-testgen-help/validity-tests/a/decimal-truncation',
  [TestgenTestType.DateCount]: 'https://docs.datakitchen.io/article/dataops-testgen-help/timeliness-tests/a/date-count',
  [TestgenTestType.ValueCount]: 'https://docs.datakitchen.io/article/dataops-testgen-help/validity-tests/a/value-count',
  [TestgenTestType.EmailFormat]: 'https://docs.datakitchen.io/article/dataops-testgen-help/validity-tests/a/email-format',
  [TestgenTestType.PastDates]: 'https://docs.datakitchen.io/article/dataops-testgen-help/timeliness-tests/a/past-dates',
  [TestgenTestType.FutureYear]: 'https://docs.datakitchen.io/article/dataops-testgen-help/timeliness-tests/a/future-year',
  [TestgenTestType.NewShift]: 'https://docs.datakitchen.io/article/dataops-testgen-help/accuracy-tests/a/new-shift',
  [TestgenTestType.AllValues]: 'https://docs.datakitchen.io/article/dataops-testgen-help/validity-tests/a/all-values',
  [TestgenTestType.ValueMatch]: 'https://docs.datakitchen.io/article/dataops-testgen-help/validity-tests/a/value-match',
  [TestgenTestType.MinimumDate]: 'https://docs.datakitchen.io/article/dataops-testgen-help/validity-tests/a/minimum-date',
  [TestgenTestType.MinimumValue]: 'https://docs.datakitchen.io/article/dataops-testgen-help/validity-tests/a/minimum-value',
  [TestgenTestType.PercentMissing]: 'https://docs.datakitchen.io/article/dataops-testgen-help/completeness-tests/a/percent-missing',
  [TestgenTestType.MonthlyRecords]: 'https://docs.datakitchen.io/article/dataops-testgen-help/completeness-tests/a/monthly-records',
  [TestgenTestType.OutliersAbove]: 'https://docs.datakitchen.io/article/dataops-testgen-help/accuracy-tests/a/outliers-above',
  [TestgenTestType.OutliersBelow]: 'https://docs.datakitchen.io/article/dataops-testgen-help/accuracy-tests/a/outliers-below',
  [TestgenTestType.PatternMatch]: 'https://docs.datakitchen.io/article/dataops-testgen-help/validity-tests/a/pattern-match',
  [TestgenTestType.Recency]: 'https://docs.datakitchen.io/article/dataops-testgen-help/timeliness-tests/a/recency',
  [TestgenTestType.RequiredEntry]: 'https://docs.datakitchen.io/article/dataops-testgen-help/completeness-tests/a/required-entry',
  [TestgenTestType.RowCount]: 'https://docs.datakitchen.io/article/dataops-testgen-help/completeness-tests/a/row-count',
  [TestgenTestType.RowRange]: 'https://docs.datakitchen.io/article/dataops-testgen-help/completeness-tests/a/row-range',
  [TestgenTestType.StreetAddress]: 'https://docs.datakitchen.io/article/dataops-testgen-help/validity-tests/a/street-address',
  [TestgenTestType.UniqueValues]: 'https://docs.datakitchen.io/article/dataops-testgen-help/uniqueness-tests/a/unique-value',
  [TestgenTestType.PercentUnique]: 'https://docs.datakitchen.io/article/dataops-testgen-help/uniqueness-tests/a/percent-unique',
  [TestgenTestType.USState]: 'https://docs.datakitchen.io/article/dataops-testgen-help/validity-tests/a/us-state',
  [TestgenTestType.WeeklyRecords]: 'https://docs.datakitchen.io/article/dataops-testgen-help/completeness-tests/a/weekly-records',
  [TestgenTestType.CustomCondition]: 'https://docs.datakitchen.io/article/dataops-testgen-help/validity-tests/a/custom-condition',
  [TestgenTestType.AggregateMinimum]: 'https://docs.datakitchen.io/article/dataops-testgen-help/accuracy-tests/a/aggregate-minimum',
  [TestgenTestType.AggregateMatch]: 'https://docs.datakitchen.io/article/dataops-testgen-help/consistency-tests/a/aggregate-match',
  [TestgenTestType.ComboMatch]: 'https://docs.datakitchen.io/article/dataops-testgen-help/validity-tests/a/combo-match',
  [TestgenTestType.PriorMatch]: 'https://docs.datakitchen.io/article/dataops-testgen-help/consistency-tests/a/prior-match',
  [TestgenTestType.DistributionShift]: 'https://docs.datakitchen.io/article/dataops-testgen-help/consistency-tests/a/distribution-shift',
  [TestgenTestType.TimeframeMinimum]: 'https://docs.datakitchen.io/article/dataops-testgen-help/consistency-tests/a/timeframe-minimum',
  [TestgenTestType.TimeframeMatch]: 'https://docs.datakitchen.io/article/dataops-testgen-help/consistency-tests/a/timeframe-match',
  [TestgenTestType.CustomTest]: 'https://docs.datakitchen.io/article/dataops-testgen-help/accuracy-tests/a/custom-test',
};
