export enum TestgenTestType {
  AlphaTruncation = 'Alpha_Trunc',
  AverageShift = 'Avg_Shift',
  ConstantMatch = 'Constant',
  DailyRecords = 'Daily_Record_Ct',
  DecimalTruncation = 'Dec_Trunc',
  DateCount = 'Distinct_Date_Ct',
  ValueCount = 'Distinct_Value_Ct',
  EmailFormat = 'Email_Format',
  PastDates = 'Future_Date',
  FutureYear = 'Future_Date_1Y',
  NewShift = 'Incr_Avg_Shift',
  AllValues = 'LOV_All',
  ValueMatch = 'LOV_Match',
  MinimumDate = 'Min_Date',
  MinimumValue = 'Min_Val',
  PercentMissing = 'Missing_Pct',
  MonthlyRecords = 'Monthly_Rec_Ct',
  OutliersAbove = 'Outlier_Pct_Above',
  OutliersBelow = 'Outlier_Pct_Below',
  PatternMatch = 'Pattern_Match',
  Recency = 'Recency',
  RequiredEntry = 'Required',
  RowCount = 'Row_Ct',
  RowRange = 'Row_Ct_Pct',
  StreetAddress = 'Street_Addr_Pattern',
  UniqueValues = 'Unique',
  PercentUnique = 'Unique_Pct',
  USState = 'US_State',
  WeeklyRecords = 'Weekly_Rec_Ct',
  CustomCondition = 'Condition_Flag',
  AggregateMinimum = 'AGG MATCH NO DROPS',
  AggregateMatch = 'AGG MATCH SAME',
  ComboMatch = 'DATA_MATCH',
  PriorMatch = 'PRIOR MATCH',
  DistributionShift = 'RELATIVE ENTROPY',
  TimeframeMinimum = 'WINDOW MATCH NO DROPS',
  TimeframeMatch = 'WINDOW MATCH SAME',
  CustomTest = 'CUSTOM',
}

export const testTypeHelpLink: {[type in TestgenTestType]: string} = {
  [TestgenTestType.AlphaTruncation]: 'https://docs.datakitchen.io/testgen/generate-tests/test-types/validity-tests/#alpha-truncation',
  [TestgenTestType.AverageShift]: 'https://docs.datakitchen.io/testgen/generate-tests/test-types/consistency-tests/#average-shift',
  [TestgenTestType.ConstantMatch]: 'https://docs.datakitchen.io/testgen/generate-tests/test-types/validity-tests/#constant-match',
  [TestgenTestType.DailyRecords]: 'https://docs.datakitchen.io/testgen/generate-tests/test-types/completeness-tests/#daily-records',
  [TestgenTestType.DecimalTruncation]: 'https://docs.datakitchen.io/testgen/generate-tests/test-types/validity-tests/#decimal-truncation',
  [TestgenTestType.DateCount]: 'https://docs.datakitchen.io/testgen/generate-tests/test-types/timeliness-tests/#date-count',
  [TestgenTestType.ValueCount]: 'https://docs.datakitchen.io/testgen/generate-tests/test-types/validity-tests/#value-count',
  [TestgenTestType.EmailFormat]: 'https://docs.datakitchen.io/testgen/generate-tests/test-types/validity-tests/#email-format',
  [TestgenTestType.PastDates]: 'https://docs.datakitchen.io/testgen/generate-tests/test-types/timeliness-tests/#past-dates',
  [TestgenTestType.FutureYear]: 'https://docs.datakitchen.io/testgen/generate-tests/test-types/timeliness-tests/#future-year',
  [TestgenTestType.NewShift]: 'https://docs.datakitchen.io/testgen/generate-tests/test-types/accuracy-tests/#new-shift',
  [TestgenTestType.AllValues]: 'https://docs.datakitchen.io/testgen/generate-tests/test-types/validity-tests/#value-match-all',
  [TestgenTestType.ValueMatch]: 'https://docs.datakitchen.io/testgen/generate-tests/test-types/validity-tests/#value-match',
  [TestgenTestType.MinimumDate]: 'https://docs.datakitchen.io/testgen/generate-tests/test-types/validity-tests/#minimum-date',
  [TestgenTestType.MinimumValue]: 'https://docs.datakitchen.io/testgen/generate-tests/test-types/validity-tests/#minimum-value',
  [TestgenTestType.PercentMissing]: 'https://docs.datakitchen.io/testgen/generate-tests/test-types/completeness-tests/#percent-missing',
  [TestgenTestType.MonthlyRecords]: 'https://docs.datakitchen.io/testgen/generate-tests/test-types/completeness-tests/#monthly-records',
  [TestgenTestType.OutliersAbove]: 'https://docs.datakitchen.io/testgen/generate-tests/test-types/accuracy-tests/#outliers-above',
  [TestgenTestType.OutliersBelow]: 'https://docs.datakitchen.io/testgen/generate-tests/test-types/accuracy-tests/#outliers-below',
  [TestgenTestType.PatternMatch]: 'https://docs.datakitchen.io/testgen/generate-tests/test-types/validity-tests/#pattern-match',
  [TestgenTestType.Recency]: 'https://docs.datakitchen.io/testgen/generate-tests/test-types/timeliness-tests/#recency',
  [TestgenTestType.RequiredEntry]: 'https://docs.datakitchen.io/testgen/generate-tests/test-types/completeness-tests/#required-entry',
  [TestgenTestType.RowCount]: 'https://docs.datakitchen.io/testgen/generate-tests/test-types/completeness-tests/#row-count',
  [TestgenTestType.RowRange]: 'https://docs.datakitchen.io/testgen/generate-tests/test-types/completeness-tests/#row-range',
  [TestgenTestType.StreetAddress]: 'https://docs.datakitchen.io/testgen/generate-tests/test-types/validity-tests/#street-address',
  [TestgenTestType.UniqueValues]: 'https://docs.datakitchen.io/testgen/generate-tests/test-types/uniqueness-tests/#unique-values',
  [TestgenTestType.PercentUnique]: 'https://docs.datakitchen.io/testgen/generate-tests/test-types/uniqueness-tests/#percent-unique',
  [TestgenTestType.USState]: 'https://docs.datakitchen.io/testgen/generate-tests/test-types/validity-tests/#us-state',
  [TestgenTestType.WeeklyRecords]: 'https://docs.datakitchen.io/testgen/generate-tests/test-types/completeness-tests/#weekly-records',
  [TestgenTestType.CustomCondition]: 'https://docs.datakitchen.io/testgen/generate-tests/test-types/validity-tests/#custom-condition',
  [TestgenTestType.AggregateMinimum]: 'https://docs.datakitchen.io/testgen/generate-tests/test-types/accuracy-tests/#aggregate-minimum',
  [TestgenTestType.AggregateMatch]: 'https://docs.datakitchen.io/testgen/generate-tests/test-types/consistency-tests/#aggregate-balance',
  [TestgenTestType.ComboMatch]: 'https://docs.datakitchen.io/testgen/generate-tests/test-types/validity-tests/#reference-match',
  [TestgenTestType.PriorMatch]: 'https://docs.datakitchen.io/testgen/generate-tests/test-types/consistency-tests/#aggregate-balance',
  [TestgenTestType.DistributionShift]: 'https://docs.datakitchen.io/testgen/generate-tests/test-types/consistency-tests/#distribution-shift',
  [TestgenTestType.TimeframeMinimum]: 'https://docs.datakitchen.io/testgen/generate-tests/test-types/consistency-tests/#timeframe-no-drops',
  [TestgenTestType.TimeframeMatch]: 'https://docs.datakitchen.io/testgen/generate-tests/test-types/consistency-tests/#timeframe-match',
  [TestgenTestType.CustomTest]: 'https://docs.datakitchen.io/testgen/generate-tests/test-types/accuracy-tests/#custom-test',
};
