#
# Values for minikube deployment
#

observability:
  flask_debug: "true"
  image:
    repository: "datakitchen"
    tag: "latest"

observability_ui:
  enable: true
  image:
    pullPolicy: Never

observability_api:
  image:
    pullPolicy: Never
  service:
    type: NodePort
    nodePort: 5000

event_api:
  image:
    pullPolicy: Never
  service:
    type: NodePort
    nodePort: 5001

agent_api:
  image:
    pullPolicy: Never
  service:
    type: NodePort
    nodePort: 5003

event_store:
  image:
    pullPolicy: Never

run_manager:
  image:
    pullPolicy: Never

rules_engine:
  image:
    pullPolicy: Never

scheduler:
  image:
    pullPolicy: Never

cli_hook:
  image:
    pullPolicy: Never
