apiVersion: v2
name: dataops-observability-services
type: application
description: DataOps Observability Supporting Services
home: https://datakitchen.io
icon: https://cloud.datakitchen.io/assets/image/dk-logo.svg
keywords:
  - datakitchen
  - dataops
maintainers:
  - name: DataKitchen
    url: https://datakitchen.io

appVersion: "2"
version: "3.0.0"
