fullnameOverride: obs-services

mysql:
  enabled: true
  replicaCount: 1
  image:
    repository: mysql
    tag: "8.4"
    pullPolicy: IfNotPresent
  auth:
    database: datakitchen
    user: observability
    passwordKey: mysql-password
    rootPasswordKey: mysql-root-password
  storage:
    size: 10Gi
    storageClass: null
  resources: {}

kafka:
  enabled: true
  image:
    repository: apache/kafka
    tag: "3.9.1"
    pullPolicy: IfNotPresent
  storage:
    size: 10Gi
    storageClass: null
  resources: {}
  topics:
    - IdentifiedEvents
    - UnidentifiedEvents
    - ScheduledEvents
    - DeadLetterOffice

service:
  type: ClusterIP

secret:
  name: mysql
