[supervisord]
nodaemon=true
user=observability
logfile=/dev/stdout
logfile_maxbytes = 0
pidfile=/dk/var/supervisord.pid
childlogdir=/dk/var/logs
strip_ansi=false

; This section is only needed for the supervisorctl command to work
[unix_http_server]
file=/dk/var/supervisor.sock

; This section is only needed for the supervisorctl command to work
[supervisorctl]
serverurl=unix:///dk/var/supervisor.sock

; This section is only needed for the supervisorctl command to work
[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[program:scheduler]
command=/dk/bin/scheduler
directory=/dk
autostart=true
autorestart=true
startsecs=2
stopwaitsecs=30

[program:run_manager]
command=/dk/bin/run-manager
directory=/dk
autostart=true
autorestart=true
startsecs=2
stopwaitsecs=30

[program:rules_engine]
command=/dk/bin/rules-engine
directory=/dk
autostart=true
autorestart=true
startsecs=2
stopwaitsecs=30

[program:observability_api]
command=/dk/bin/gunicorn -c /dk/gunicorn.conf.py --bind 0.0.0.0:5000 observability_api.app:app
directory=/dk
autostart=true
autorestart=true
startsecs=2
stopwaitsecs=30

[program:event_api]
command=/dk/bin/gunicorn -c /dk/gunicorn.conf.py --bind 0.0.0.0:5001 event_api.app:app
directory=/dk
autostart=true
autorestart=true
startsecs=2
stopwaitsecs=30

[program:agent_api]
command=/dk/bin/gunicorn -c /dk/gunicorn.conf.py --bind 0.0.0.0:5003 agent_api.app:app
directory=/dk
autostart=true
autorestart=true
startsecs=2
stopwaitsecs=30
